import { defineStore } from 'pinia'
import { ref, computed } from 'vue'
import type { Company } from '../components/companies/types'

export const useCompaniesStore = defineStore('companies', () => {
  const companies = ref<Company[]>([
    {
      id: 1,
      name: 'Acme Corporation',
      email: 'contact@acme.com',
      subscription: 'enterprise',
      status: 'active',
      users: 45,
      createdAt: '2024-01-15',
      phone: '+1 (555) 123-4567',
      website: 'https://acme.com',
      industry: 'Technology',
      companySize: '201-500',
      billingCycle: 'annually',
      billingEmail: 'billing@acme.com',
      billingAddress: '123 Innovation Drive',
      billingCity: 'San Francisco',
      billingCountry: 'United States',
      adminFirstName: 'John',
      adminLastName: 'Smith',
      adminEmail: 'john.smith@acme.com',
      adminPhone: '+1 (555) 123-4568',
      adminRole: 'CEO',
    },
    {
      id: 2,
      name: 'TechStart Inc',
      email: 'hello@techstart.io',
      subscription: 'professional',
      status: 'active',
      users: 12,
      createdAt: '2024-02-20',
      phone: '+1 (555) 234-5678',
      website: 'https://techstart.io',
      industry: 'Technology',
      companySize: '11-50',
      billingCycle: 'monthly',
      billingEmail: 'finance@techstart.io',
      billingAddress: '456 Startup Lane',
      billingCity: 'Austin',
      billingCountry: 'United States',
      adminFirstName: 'Sarah',
      adminLastName: 'Johnson',
      adminEmail: 'sarah@techstart.io',
      adminPhone: '+1 (555) 234-5679',
      adminRole: 'CTO',
    },
    {
      id: 3,
      name: 'Global Solutions Ltd',
      email: 'info@globalsolutions.com',
      subscription: 'enterprise',
      status: 'active',
      users: 78,
      createdAt: '2023-11-08',
      phone: '+44 20 7946 0958',
      website: 'https://globalsolutions.com',
      industry: 'Consulting',
      companySize: '500+',
      billingCycle: 'annually',
      billingEmail: 'accounts@globalsolutions.com',
      billingAddress: '789 Business Park',
      billingCity: 'London',
      billingCountry: 'United Kingdom',
      adminFirstName: 'James',
      adminLastName: 'Williams',
      adminEmail: 'j.williams@globalsolutions.com',
      adminPhone: '+44 20 7946 0959',
      adminRole: 'Managing Director',
    },
    {
      id: 4,
      name: 'StartupHub',
      email: 'team@startuphub.co',
      subscription: 'starter',
      status: 'pending',
      users: 3,
      createdAt: '2024-03-01',
      phone: '+1 (555) 345-6789',
      website: 'https://startuphub.co',
      industry: 'Technology',
      companySize: '1-10',
      billingCycle: 'monthly',
      billingEmail: 'billing@startuphub.co',
      billingAddress: '101 Coworking Space',
      billingCity: 'Denver',
      billingCountry: 'United States',
      adminFirstName: 'Mike',
      adminLastName: 'Chen',
      adminEmail: 'mike@startuphub.co',
      adminPhone: '+1 (555) 345-6790',
      adminRole: 'Founder',
    },
    {
      id: 5,
      name: 'Digital Dynamics',
      email: 'support@digitaldynamics.net',
      subscription: 'professional',
      status: 'active',
      users: 25,
      createdAt: '2024-01-28',
      phone: '+1 (555) 456-7890',
      website: 'https://digitaldynamics.net',
      industry: 'Technology',
      companySize: '11-50',
      billingCycle: 'annually',
      billingEmail: 'invoices@digitaldynamics.net',
      billingAddress: '222 Digital Avenue',
      billingCity: 'Seattle',
      billingCountry: 'United States',
      adminFirstName: 'Emily',
      adminLastName: 'Davis',
      adminEmail: 'emily.davis@digitaldynamics.net',
      adminPhone: '+1 (555) 456-7891',
      adminRole: 'Operations Manager',
    },
    {
      id: 6,
      name: 'CloudNine Systems',
      email: 'admin@cloudnine.io',
      subscription: 'enterprise',
      status: 'inactive',
      users: 0,
      createdAt: '2023-09-15',
      phone: '+1 (555) 567-8901',
      website: 'https://cloudnine.io',
      industry: 'Technology',
      companySize: '51-200',
      billingCycle: 'annually',
      billingEmail: 'billing@cloudnine.io',
      billingAddress: '333 Cloud Street',
      billingCity: 'Portland',
      billingCountry: 'United States',
      adminFirstName: 'Robert',
      adminLastName: 'Taylor',
      adminEmail: 'robert@cloudnine.io',
      adminPhone: '+1 (555) 567-8902',
      adminRole: 'VP Engineering',
    },
    {
      id: 7,
      name: 'InnovateTech',
      email: 'contact@innovatetech.com',
      subscription: 'starter',
      status: 'active',
      users: 5,
      createdAt: '2024-02-10',
      phone: '+1 (555) 678-9012',
      website: 'https://innovatetech.com',
      industry: 'Technology',
      companySize: '1-10',
      billingCycle: 'monthly',
      billingEmail: 'pay@innovatetech.com',
      billingAddress: '444 Innovation Blvd',
      billingCity: 'Boston',
      billingCountry: 'United States',
      adminFirstName: 'Lisa',
      adminLastName: 'Anderson',
      adminEmail: 'lisa@innovatetech.com',
      adminPhone: '+1 (555) 678-9013',
      adminRole: 'CEO',
    },
    {
      id: 8,
      name: 'DataFlow Analytics',
      email: 'hello@dataflow.ai',
      subscription: 'professional',
      status: 'active',
      users: 18,
      createdAt: '2024-01-05',
      phone: '+1 (555) 789-0123',
      website: 'https://dataflow.ai',
      industry: 'Technology',
      companySize: '11-50',
      billingCycle: 'annually',
      billingEmail: 'accounting@dataflow.ai',
      billingAddress: '555 Data Drive',
      billingCity: 'Chicago',
      billingCountry: 'United States',
      adminFirstName: 'David',
      adminLastName: 'Martinez',
      adminEmail: 'david@dataflow.ai',
      adminPhone: '+1 (555) 789-0124',
      adminRole: 'Chief Data Officer',
    },
    {
      id: 9,
      name: 'NextGen Labs',
      email: 'info@nextgenlabs.io',
      subscription: 'enterprise',
      status: 'active',
      users: 52,
      createdAt: '2023-12-01',
      phone: '+1 (555) 890-1234',
      website: 'https://nextgenlabs.io',
      industry: 'Healthcare',
      companySize: '51-200',
      billingCycle: 'annually',
      billingEmail: 'finance@nextgenlabs.io',
      billingAddress: '666 Research Park',
      billingCity: 'San Diego',
      billingCountry: 'United States',
      adminFirstName: 'Jennifer',
      adminLastName: 'Wilson',
      adminEmail: 'j.wilson@nextgenlabs.io',
      adminPhone: '+1 (555) 890-1235',
      adminRole: 'Director of Operations',
    },
    {
      id: 10,
      name: 'Quantum Computing Inc',
      email: 'support@quantumcomp.com',
      subscription: 'enterprise',
      status: 'active',
      users: 89,
      createdAt: '2023-08-22',
      phone: '+1 (555) 901-2345',
      website: 'https://quantumcomp.com',
      industry: 'Technology',
      companySize: '201-500',
      billingCycle: 'annually',
      billingEmail: 'ap@quantumcomp.com',
      billingAddress: '777 Quantum Way',
      billingCity: 'Mountain View',
      billingCountry: 'United States',
      adminFirstName: 'Michael',
      adminLastName: 'Brown',
      adminEmail: 'm.brown@quantumcomp.com',
      adminPhone: '+1 (555) 901-2346',
      adminRole: 'CTO',
    },
    {
      id: 11,
      name: 'Green Energy Solutions',
      email: 'contact@greenenergy.org',
      subscription: 'professional',
      status: 'active',
      users: 34,
      createdAt: '2024-01-10',
      phone: '+1 (555) 012-3456',
      website: 'https://greenenergy.org',
      industry: 'Manufacturing',
      companySize: '51-200',
      billingCycle: 'annually',
      billingEmail: 'billing@greenenergy.org',
      billingAddress: '888 Sustainable Ave',
      billingCity: 'Phoenix',
      billingCountry: 'United States',
      adminFirstName: 'Amanda',
      adminLastName: 'Garcia',
      adminEmail: 'amanda@greenenergy.org',
      adminPhone: '+1 (555) 012-3457',
      adminRole: 'Sustainability Director',
    },
    {
      id: 12,
      name: 'FinTech Pro',
      email: 'hello@fintechpro.com',
      subscription: 'enterprise',
      status: 'pending',
      users: 0,
      createdAt: '2024-03-05',
      phone: '+1 (555) 111-2222',
      website: 'https://fintechpro.com',
      industry: 'Finance',
      companySize: '51-200',
      billingCycle: 'annually',
      billingEmail: 'accounts@fintechpro.com',
      billingAddress: '999 Financial District',
      billingCity: 'New York',
      billingCountry: 'United States',
      adminFirstName: 'Christopher',
      adminLastName: 'Lee',
      adminEmail: 'chris.lee@fintechpro.com',
      adminPhone: '+1 (555) 111-2223',
      adminRole: 'CFO',
    },
    {
      id: 13,
      name: 'HealthCare Plus',
      email: 'admin@healthcareplus.net',
      subscription: 'professional',
      status: 'active',
      users: 41,
      createdAt: '2023-10-15',
      phone: '+1 (555) 222-3333',
      website: 'https://healthcareplus.net',
      industry: 'Healthcare',
      companySize: '51-200',
      billingCycle: 'annually',
      billingEmail: 'billing@healthcareplus.net',
      billingAddress: '100 Medical Center Blvd',
      billingCity: 'Houston',
      billingCountry: 'United States',
      adminFirstName: 'Patricia',
      adminLastName: 'Thomas',
      adminEmail: 'p.thomas@healthcareplus.net',
      adminPhone: '+1 (555) 222-3334',
      adminRole: 'Administrator',
    },
    {
      id: 14,
      name: 'EduTech Academy',
      email: 'info@edutechacademy.com',
      subscription: 'starter',
      status: 'active',
      users: 8,
      createdAt: '2024-02-01',
      phone: '+1 (555) 333-4444',
      website: 'https://edutechacademy.com',
      industry: 'Education',
      companySize: '1-10',
      billingCycle: 'monthly',
      billingEmail: 'finance@edutechacademy.com',
      billingAddress: '200 Learning Lane',
      billingCity: 'Miami',
      billingCountry: 'United States',
      adminFirstName: 'Kevin',
      adminLastName: 'White',
      adminEmail: 'kevin@edutechacademy.com',
      adminPhone: '+1 (555) 333-4445',
      adminRole: 'Principal',
    },
    {
      id: 15,
      name: 'Cyber Shield Security',
      email: 'security@cybershield.io',
      subscription: 'enterprise',
      status: 'active',
      users: 67,
      createdAt: '2023-07-20',
      phone: '+1 (555) 444-5555',
      website: 'https://cybershield.io',
      industry: 'Technology',
      companySize: '51-200',
      billingCycle: 'annually',
      billingEmail: 'invoices@cybershield.io',
      billingAddress: '300 Security Plaza',
      billingCity: 'Washington',
      billingCountry: 'United States',
      adminFirstName: 'Daniel',
      adminLastName: 'Harris',
      adminEmail: 'd.harris@cybershield.io',
      adminPhone: '+1 (555) 444-5556',
      adminRole: 'CISO',
    },
    {
      id: 16,
      name: 'Smart Home Tech',
      email: 'support@smarthometech.com',
      subscription: 'professional',
      status: 'inactive',
      users: 0,
      createdAt: '2023-11-30',
      phone: '+1 (555) 555-6666',
      website: 'https://smarthometech.com',
      industry: 'Technology',
      companySize: '11-50',
      billingCycle: 'monthly',
      billingEmail: 'pay@smarthometech.com',
      billingAddress: '400 IoT Boulevard',
      billingCity: 'Atlanta',
      billingCountry: 'United States',
      adminFirstName: 'Nancy',
      adminLastName: 'Clark',
      adminEmail: 'nancy@smarthometech.com',
      adminPhone: '+1 (555) 555-6667',
      adminRole: 'Product Manager',
    },
    {
      id: 17,
      name: 'AI Solutions Corp',
      email: 'contact@aisolutions.ai',
      subscription: 'enterprise',
      status: 'active',
      users: 112,
      createdAt: '2023-06-15',
      phone: '+1 (555) 666-7777',
      website: 'https://aisolutions.ai',
      industry: 'Technology',
      companySize: '201-500',
      billingCycle: 'annually',
      billingEmail: 'ar@aisolutions.ai',
      billingAddress: '500 AI Campus',
      billingCity: 'Palo Alto',
      billingCountry: 'United States',
      adminFirstName: 'Steven',
      adminLastName: 'Robinson',
      adminEmail: 's.robinson@aisolutions.ai',
      adminPhone: '+1 (555) 666-7778',
      adminRole: 'CEO',
    },
    {
      id: 18,
      name: 'Mobile First Apps',
      email: 'hello@mobilefirst.dev',
      subscription: 'starter',
      status: 'active',
      users: 6,
      createdAt: '2024-02-28',
      phone: '+1 (555) 777-8888',
      website: 'https://mobilefirst.dev',
      industry: 'Technology',
      companySize: '1-10',
      billingCycle: 'monthly',
      billingEmail: 'billing@mobilefirst.dev',
      billingAddress: '600 App Street',
      billingCity: 'Los Angeles',
      billingCountry: 'United States',
      adminFirstName: 'Jessica',
      adminLastName: 'Lewis',
      adminEmail: 'jessica@mobilefirst.dev',
      adminPhone: '+1 (555) 777-8889',
      adminRole: 'Lead Developer',
    },
    {
      id: 19,
      name: 'Cloud Infrastructure Ltd',
      email: 'ops@cloudinfra.io',
      subscription: 'enterprise',
      status: 'active',
      users: 95,
      createdAt: '2023-09-01',
      phone: '+1 (555) 888-9999',
      website: 'https://cloudinfra.io',
      industry: 'Technology',
      companySize: '201-500',
      billingCycle: 'annually',
      billingEmail: 'finance@cloudinfra.io',
      billingAddress: '700 Server Farm Road',
      billingCity: 'Dallas',
      billingCountry: 'United States',
      adminFirstName: 'Mark',
      adminLastName: 'Walker',
      adminEmail: 'mark.walker@cloudinfra.io',
      adminPhone: '+1 (555) 888-9990',
      adminRole: 'VP Infrastructure',
    },
    {
      id: 20,
      name: 'Social Media Hub',
      email: 'team@socialmediahub.com',
      subscription: 'professional',
      status: 'active',
      users: 28,
      createdAt: '2024-01-20',
      phone: '+1 (555) 999-0000',
      website: 'https://socialmediahub.com',
      industry: 'Technology',
      companySize: '11-50',
      billingCycle: 'monthly',
      billingEmail: 'accounts@socialmediahub.com',
      billingAddress: '800 Social Street',
      billingCity: 'Nashville',
      billingCountry: 'United States',
      adminFirstName: 'Ashley',
      adminLastName: 'Hall',
      adminEmail: 'ashley@socialmediahub.com',
      adminPhone: '+1 (555) 999-0001',
      adminRole: 'Marketing Director',
    },
    {
      id: 21,
      name: 'E-Commerce Express',
      email: 'sales@ecomexpress.com',
      subscription: 'professional',
      status: 'active',
      users: 37,
      createdAt: '2023-12-10',
      phone: '+1 (555) 100-2000',
      website: 'https://ecomexpress.com',
      industry: 'Retail',
      companySize: '51-200',
      billingCycle: 'annually',
      billingEmail: 'billing@ecomexpress.com',
      billingAddress: '900 Commerce Way',
      billingCity: 'Philadelphia',
      billingCountry: 'United States',
      adminFirstName: 'Brian',
      adminLastName: 'Young',
      adminEmail: 'brian@ecomexpress.com',
      adminPhone: '+1 (555) 100-2001',
      adminRole: 'Sales Director',
    },
    {
      id: 22,
      name: 'Virtual Reality Labs',
      email: 'info@vrlabs.tech',
      subscription: 'starter',
      status: 'pending',
      users: 2,
      createdAt: '2024-03-08',
      phone: '+1 (555) 200-3000',
      website: 'https://vrlabs.tech',
      industry: 'Technology',
      companySize: '1-10',
      billingCycle: 'monthly',
      billingEmail: 'pay@vrlabs.tech',
      billingAddress: '1000 VR Lane',
      billingCity: 'San Jose',
      billingCountry: 'United States',
      adminFirstName: 'Ryan',
      adminLastName: 'King',
      adminEmail: 'ryan@vrlabs.tech',
      adminPhone: '+1 (555) 200-3001',
      adminRole: 'Founder',
    },
    {
      id: 23,
      name: 'Blockchain Ventures',
      email: 'contact@blockchainv.io',
      subscription: 'enterprise',
      status: 'active',
      users: 54,
      createdAt: '2023-10-05',
      phone: '+1 (555) 300-4000',
      website: 'https://blockchainv.io',
      industry: 'Finance',
      companySize: '51-200',
      billingCycle: 'annually',
      billingEmail: 'treasury@blockchainv.io',
      billingAddress: '1100 Crypto Plaza',
      billingCity: 'Miami',
      billingCountry: 'United States',
      adminFirstName: 'Andrew',
      adminLastName: 'Wright',
      adminEmail: 'andrew@blockchainv.io',
      adminPhone: '+1 (555) 300-4001',
      adminRole: 'Managing Partner',
    },
    {
      id: 24,
      name: 'DevOps Masters',
      email: 'support@devopsmasters.com',
      subscription: 'professional',
      status: 'active',
      users: 19,
      createdAt: '2024-01-25',
      phone: '+1 (555) 400-5000',
      website: 'https://devopsmasters.com',
      industry: 'Technology',
      companySize: '11-50',
      billingCycle: 'annually',
      billingEmail: 'invoicing@devopsmasters.com',
      billingAddress: '1200 Pipeline Road',
      billingCity: 'Raleigh',
      billingCountry: 'United States',
      adminFirstName: 'Joshua',
      adminLastName: 'Scott',
      adminEmail: 'josh@devopsmasters.com',
      adminPhone: '+1 (555) 400-5001',
      adminRole: 'DevOps Lead',
    },
    {
      id: 25,
      name: 'Data Science Co',
      email: 'hello@datascienceco.ai',
      subscription: 'enterprise',
      status: 'active',
      users: 73,
      createdAt: '2023-08-10',
      phone: '+1 (555) 500-6000',
      website: 'https://datascienceco.ai',
      industry: 'Technology',
      companySize: '51-200',
      billingCycle: 'annually',
      billingEmail: 'accounts@datascienceco.ai',
      billingAddress: '1300 Analytics Drive',
      billingCity: 'Cambridge',
      billingCountry: 'United States',
      adminFirstName: 'Michelle',
      adminLastName: 'Green',
      adminEmail: 'michelle@datascienceco.ai',
      adminPhone: '+1 (555) 500-6001',
      adminRole: 'Chief Data Scientist',
    },
  ])

  const totalCompanies = computed(() => companies.value.length)

  function getCompanyById(id: number): Company | undefined {
    return companies.value.find(c => c.id === id)
  }

  function addCompany(companyData: Omit<Company, 'id' | 'users' | 'createdAt' | 'status'>) {
    const newCompany: Company = {
      id: Math.max(...companies.value.map(c => c.id)) + 1,
      ...companyData,
      status: 'pending',
      users: 0,
      createdAt: new Date().toISOString().split('T')[0],
    }
    companies.value.unshift(newCompany)
    return newCompany
  }

  function updateCompany(id: number, updates: Partial<Company>) {
    const index = companies.value.findIndex(c => c.id === id)
    if (index !== -1) {
      companies.value[index] = { ...companies.value[index], ...updates }
      return companies.value[index]
    }
    return null
  }

  function deleteCompany(id: number) {
    const index = companies.value.findIndex(c => c.id === id)
    if (index !== -1) {
      companies.value.splice(index, 1)
      return true
    }
    return false
  }

  return {
    companies,
    totalCompanies,
    getCompanyById,
    addCompany,
    updateCompany,
    deleteCompany,
  }
})
